# Name of the workflow
name: Testing Server

# Events that trigger the workflow
on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
  # Also trigger the workflow on pull request events to the main branch
  pull_request:
    branches:
      - main

# Jobs that the workflow will run
jobs:
  # Name of the job
  Running_Flask_tests:
    
    runs-on: ubuntu-latest

    # This allows the job to access the MongoDB service to run tests successfully
    services:
      mongodb:
        image: mongo:4.2
        ports:
          - 27017:27017

    # Steps that the job will run
    steps:
    # Checks out a copy of your repository on the runner
    - name: Checkout branch
      uses: actions/checkout@v2

    # Sets up the specified Python version
    - name: Set up Python to v3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    # Caches dependencies to speed up the workflow
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Installs dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install pytest
    - name: Install pytest
      run: |
        pip install pytest

    # Runs tests
    - name: Run tests
      run: pytest
